=== mohamedYoussfi/xml-bourse/bourse.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bourse (societe+) >
<!ELEMENT societe (code, nom, dateIntro, cotations) >
<!ELEMENT code (#PCDATA) >
<!ELEMENT nom (#PCDATA) >
<!ELEMENT dateIntro (#PCDATA) >
<!ELEMENT cotations (cotation+) >
<!ELEMENT cotation EMPTY >
<!ATTLIST societe 
                    type (banque|assurance) "banque" >
<!ATTLIST cotation
                    num NMTOKEN #REQUIRED
                    date CDATA #REQUIRED
                    valAction CDATA #REQUIRED>

=== mohamedYoussfi/xml-bourse/bourse.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bourse SYSTEM "file:/C:/TPXML/bourse/bourse.dtd">
<bourse>
    <societe type="banque">
        <code>SG</code>
        <nom>SG</nom>
        <dateIntro>2012-11-11</dateIntro>
        <cotations>
            <cotation num="1" date="2012-12-12" valAction="760"/>
            <cotation num="1" date="2012-12-13" valAction="750"/>
            <cotation num="1" date="2012-12-14" valAction="700"/>
            <cotation num="1" date="2012-12-15" valAction="766"/>
        </cotations>
    </societe>
    <societe type="banque">
        <code>CIH</code>
        <nom>CIH</nom>
        <dateIntro>2012-11-11</dateIntro>
        <cotations>
            <cotation num="1" date="2012-12-12" valAction="760"/>
            <cotation num="1" date="2012-12-13" valAction="750"/>
            <cotation num="1" date="2012-12-14" valAction="700"/>
            <cotation num="1" date="2012-12-15" valAction="766"/>
        </cotations>
    </societe>
    <societe type="assurance">
        <code>AXA</code>
        <nom>AXA</nom>
        <dateIntro>2012-01-01</dateIntro>
        <cotations>
            <cotation num="11" date="2012-12-12" valAction="260"/>
            <cotation num="12" date="2012-12-13" valAction="277"/>
            <cotation num="13" date="2012-12-14" valAction="282"/>
            <cotation num="14" date="2012-12-15" valAction="210"/>
        </cotations>
    </societe>
</bourse>
